services:
  bidflow_db:
    image: pgvector/pgvector:pg16 # 👈 Alterado para a tag oficial correta (Postgres 16)
    container_name: bidflow_db_v2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: bidflow
    volumes:
      - bidflow_postgres_v2:/var/lib/postgresql/data

  bidflow_mq:
    image: rabbitmq:3-management-alpine
    container_name: bidflow_rabbitmq_v2
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - bidflow_rabbitmq_data_v2:/var/lib/rabbitmq

volumes:
  bidflow_postgres_v2:
  bidflow_rabbitmq_data_v2: