export enum StageType {
  INITIAL = 'INITIAL',
  STANDARD = 'STANDARD',
  APPROVAL = 'APPROVAL',
  REVIEW = 'REVIEW',
  FINISH = 'FINISH',
  CANCELLED = 'CANCELLED',
}

export enum InstanceStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum InstancePriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum ApprovalMode {
  ANY = 'ANY',
  ALL = 'ALL',
  SEQUENTIAL = 'SEQUENTIAL',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SKIPPED = 'SKIPPED',
  EXPIRED = 'EXPIRED',
}

export enum AssignmentStatus {
  ACTIVE = 'ACTIVE',
  DELEGATED = 'DELEGATED',
  COMPLETED = 'COMPLETED',
  REVOKED = 'REVOKED',
}

export enum TaskType {
  ACTION = 'ACTION',
  UPLOAD = 'UPLOAD',
  FORM = 'FORM',
  VALIDATION = 'VALIDATION',
  NOTIFICATION = 'NOTIFICATION',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
}

export enum TimelineEntryType {
  INSTANCE_CREATED = 'INSTANCE_CREATED',
  STAGE_ENTERED = 'STAGE_ENTERED',
  STAGE_EXITED = 'STAGE_EXITED',
  TRANSITION_EXECUTED = 'TRANSITION_EXECUTED',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  ASSIGNED = 'ASSIGNED',
  REASSIGNED = 'REASSIGNED',
  DELEGATED = 'DELEGATED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  DEADLINE_UPDATED = 'DEADLINE_UPDATED',
  PRIORITY_CHANGED = 'PRIORITY_CHANGED',
  AUTO_TRANSITIONED = 'AUTO_TRANSITIONED',
  INSTANCE_COMPLETED = 'INSTANCE_COMPLETED',
  INSTANCE_CANCELLED = 'INSTANCE_CANCELLED',
  SYSTEM_EVENT = 'SYSTEM_EVENT',
}
