// @ts-nocheck
import { Controller, Logger } from '@nestjs/common';
import { EventPattern, Payload, Ctx, RmqContext } from '@nestjs/microservices';
import { InstanceOrchestrationService } from '../../application/common/services/instance-orchestration.service';
import { WorkflowDefinitionRepository } from '../../domain/definition/workflow-definition.repository';
import { WorkflowInstanceRepository } from '../../domain/instance/workflow-instance.repository';
import { WorkflowTaskRepository } from '../../domain/task/workflow-task.repository';
import { InstanceStatus } from '../../domain/common/enums';

export interface TenderCapturedPayload {
  tenderId: string;
  source: string;
  number: string;
}

export interface TenderCapturedEvent {
  eventId: string;
  aggregateId: string;
  tenantId: string;
  type: string;
  occurredAt: string;
  payload: TenderCapturedPayload;
}

export interface ProposalSubmittedPayload {
  totalValue: number;
}

export interface ProposalSubmittedEvent {
  eventId: string;
  aggregateId: string;
  tenantId: string;
  tenderId: string;
  userId?: string;
  type: string;
  occurredAt: string;
  payload: ProposalSubmittedPayload;
}

export interface ResultProcessedPayload {
  status: string;
  classification: number;
}

export interface ResultProcessedEvent {
  eventId: string;
  aggregateId: string;
  tenantId: string;
  tenderId: string;
  userId?: string;
  type: string;
  occurredAt: string;
  payload: ResultProcessedPayload;
}

@Controller()
export class TenderEventsConsumer {
  private readonly logger = new Logger(TenderEventsConsumer.name);

  constructor(
    private readonly orchestrationService: InstanceOrchestrationService,
    private readonly definitionRepository: WorkflowDefinitionRepository,
    private readonly instanceRepository: WorkflowInstanceRepository,
    private readonly taskRepository: WorkflowTaskRepository,
  ) {}

  @EventPattern('bidflow.tender.v1.captured')
  async handleTenderCaptured(
    @Payload() data: TenderCapturedEvent,
    @Ctx() context: RmqContext
  ) {
    try {
      this.logger.log(`Received tender captured event for tender: ${data.payload.tenderId}`);

      const { tenantId, payload } = data;
      const { tenderId, number, source } = payload;

      const definitions = await this.definitionRepository.findByEntityType('TENDER', tenantId);
      const activeDefinition = definitions.find(d => d.isActive);

      if (!activeDefinition) {
        this.logger.warn(`No active workflow definition found for entityType 'TENDER' and tenant '${tenantId}'. Skipping instance creation.`);
        this.ackMessage(context);
        return;
      }

      const title = `Esteira Operacional - Edital: ${number}`;
      
      const params = {
        tenantId,
        workflowDefinitionId: activeDefinition.id,
        workflowVersion: activeDefinition.version,
        entityType: 'TENDER',
        entityId: tenderId,
        title,
        priority: 'MEDIUM' as any,
        data: {
          source,
          number,
          tenderId,
          autoGenerated: true,
        },
        createdBy: 'system-consumer',
      };

      const instance = await this.orchestrationService.createInstance(params as any);

      this.logger.log(`Successfully created Workflow Instance [${instance.id}] for Tender [${tenderId}]`);
      this.ackMessage(context);
    } catch (error: any) {
      this.logger.error(`Failed to process tender captured event: ${error.message}`, error.stack);
      this.nackMessage(context);
    }
  }

  @EventPattern('bidflow.tender.v1.proposal_submitted')
  async handleProposalSubmitted(
    @Payload() data: ProposalSubmittedEvent,
    @Ctx() context: RmqContext
  ) {
    try {
      const { tenantId, tenderId, userId } = data;
      this.logger.log(`Received proposal submitted event for tender: ${tenderId}`);

      const instance = await this.instanceRepository.findByEntity('TENDER', tenderId, tenantId);
      
      if (!instance || instance.status !== InstanceStatus.IN_PROGRESS) {
        this.logger.warn(`Active workflow instance not found for Tender [${tenderId}] in Tenant [${tenantId}].`);
        this.ackMessage(context);
        return;
      }

      // Tentativa de transição via OrchestrationService
      try {
        await this.orchestrationService.executeTransition(
          instance.id, 
          'avancar_disputa', 
          userId || 'system-consumer', 
          tenantId, 
          'Avanço automático após submissão de proposta.'
        );
        this.logger.log(`Successfully transitioned Workflow Instance [${instance.id}] to dispute phase.`);
      } catch (transitionError: any) {
        this.logger.warn(`Could not execute transition 'avancar_disputa' automatically: ${transitionError.message}`);
        // Fallback: Completa a tarefa se não puder transicionar
        const tasks = await this.taskRepository.findByInstance(instance.id);
        const proposalTask = tasks.find(t => t.status === 'PENDING' && t.slug === 'ELABORAR_PROPOSTA');
        if (proposalTask) {
          proposalTask.complete(userId || 'system-consumer');
          await this.taskRepository.save(proposalTask);
          this.logger.log(`Completed task 'ELABORAR_PROPOSTA' for Workflow Instance [${instance.id}].`);
        }
      }

      this.ackMessage(context);
    } catch (error: any) {
      this.logger.error(`Failed to process proposal submitted event: ${error.message}`, error.stack);
      this.nackMessage(context);
    }
  }

  @EventPattern('bidflow.tender.v1.result_processed')
  async handleResultProcessed(
    @Payload() data: ResultProcessedEvent,
    @Ctx() context: RmqContext
  ) {
    try {
      const { tenantId, tenderId, userId, payload } = data;
      this.logger.log(`Received result processed event for tender: ${tenderId} with status: ${payload.status}`);

      const instance = await this.instanceRepository.findByEntity('TENDER', tenderId, tenantId);
      
      if (!instance || !instance.isActive) {
        this.logger.warn(`Active workflow instance not found for Tender [${tenderId}] in Tenant [${tenantId}].`);
        this.ackMessage(context);
        return;
      }

      const reason = `Edital finalizado via plataforma com status: ${payload.status}`;

      if (payload.status === 'WON' || payload.status === 'LOST') {
        instance.complete(userId || 'system-consumer');
        // Injetando no data as informações para auditoria
        instance.updateData({
          ...instance.data,
          finalResult: payload.status,
          classification: payload.classification,
          closedAt: new Date().toISOString()
        });
        await this.instanceRepository.save(instance);
        this.logger.log(`Successfully completed Workflow Instance [${instance.id}] due to result processing.`);
      } else {
        await this.orchestrationService.cancelInstance(
          instance.id, 
          reason, 
          userId || 'system-consumer', 
          tenantId
        );
        this.logger.log(`Successfully cancelled Workflow Instance [${instance.id}] due to result: ${payload.status}.`);
      }

      this.ackMessage(context);
    } catch (error: any) {
      this.logger.error(`Failed to process result processed event: ${error.message}`, error.stack);
      this.nackMessage(context);
    }
  }

  private ackMessage(context: RmqContext) {
    const channel = context.getChannelRef();
    const originalMsg = context.getMessage();
    if (channel && typeof channel.ack === 'function') {
      channel.ack(originalMsg);
    }
  }

  private nackMessage(context: RmqContext) {
    const channel = context.getChannelRef();
    const originalMsg = context.getMessage();
    if (channel && typeof channel.nack === 'function') {
      channel.nack(originalMsg, false, false);
    }
  }
}
